FROM python:3.12-slim

# Install UV package manager
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies using UV
RUN uv pip install .

# Set environment variables
ENV PORT=8080
ENV HOST=0.0.0.0

# Expose port
EXPOSE 8080

# Run Streamlit
CMD streamlit run src/streamlit/Home.py --server.port=$PORT --server.address=$HOST
