steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-f'
    - 'docker/collections.Dockerfile'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bgg-predictive-models/collections:$COMMIT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bgg-predictive-models/collections:$COMMIT_SHA'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'bgg-collection-scoring'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/bgg-predictive-models/collections:$COMMIT_SHA'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--max-instances'
    - '5'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '2'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/bgg-predictive-models/collections:$COMMIT_SHA'
