name: BGG Model Predictions

on:
  workflow_dispatch:
    inputs:
      start_year:
        description: 'Start year for predictions'
        required: false
        default: '2024'
      end_year:
        description: 'End year for predictions'
        required: false
        default: '2029'
      output_path:
        description: 'Cloud storage path for predictions'
        required: false
        default: 'gs://bgg-predictive-models-dev/predictions/game_predictions.parquet'

  schedule:
    # Run daily at 1 AM UTC
    - cron: '0 1 * * *'

jobs:
  get-latest-models:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    outputs:
      hurdle_model: ${{ steps.get-models.outputs.hurdle_model }}
      complexity_model: ${{ steps.get-models.outputs.complexity_model }}
      rating_model: ${{ steps.get-models.outputs.rating_model }}
      users_rated_model: ${{ steps.get-models.outputs.users_rated_model }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'cloud-run-predictor@YOUR_PROJECT_ID.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Get Latest Registered Models
      id: get-models
      run: |
        # Function to get latest model name
        get_latest_model() {
          local model_type=$1
          gcloud run services invoke bgg-model-scoring \
            --region us-central1 \
            --method GET \
            --uri="/models" | \
            jq -r --arg type "$model_type" '.[$type] | 
              sort_by(.version) | 
              last | 
              .name'
        }

        # Get latest models for each type
        HURDLE_MODEL=$(get_latest_model "hurdle")
        COMPLEXITY_MODEL=$(get_latest_model "complexity")
        RATING_MODEL=$(get_latest_model "rating")
        USERS_RATED_MODEL=$(get_latest_model "users_rated")

        # Output models for subsequent jobs
        echo "hurdle_model=$HURDLE_MODEL" >> $GITHUB_OUTPUT
        echo "complexity_model=$COMPLEXITY_MODEL" >> $GITHUB_OUTPUT
        echo "rating_model=$RATING_MODEL" >> $GITHUB_OUTPUT
        echo "users_rated_model=$USERS_RATED_MODEL" >> $GITHUB_OUTPUT

  trigger-predictions:
    needs: get-latest-models
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'cloud-run-predictor@YOUR_PROJECT_ID.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Trigger Cloud Run Prediction
      run: |
        gcloud run services invoke bgg-model-scoring \
          --region us-central1 \
          --method POST \
          --body '{
            "hurdle_model_name": "${{ needs.get-latest-models.outputs.hurdle_model }}",
            "complexity_model_name": "${{ needs.get-latest-models.outputs.complexity_model }}",
            "rating_model_name": "${{ needs.get-latest-models.outputs.rating_model }}",
            "users_rated_model_name": "${{ needs.get-latest-models.outputs.users_rated_model }}",
            "start_year": ${{ github.event.inputs.start_year || 2024 }},
            "end_year": ${{ github.event.inputs.end_year || 2029 }},
            "output_path": "${{ github.event.inputs.output_path || 'gs://bgg-predictive-models-dev/predictions/game_predictions.parquet' }}"
          }'

    - name: Log Prediction Metadata
      run: |
        echo "Prediction Parameters:"
        echo "Hurdle Model: ${{ needs.get-latest-models.outputs.hurdle_model }}"
        echo "Complexity Model: ${{ needs.get-latest-models.outputs.complexity_model }}"
        echo "Rating Model: ${{ needs.get-latest-models.outputs.rating_model }}"
        echo "Users Rated Model: ${{ needs.get-latest-models.outputs.users_rated_model }}"
        echo "Start Year: ${{ github.event.inputs.start_year || 2024 }}"
        echo "End Year: ${{ github.event.inputs.end_year || 2029 }}"
        echo "Output Path: ${{ github.event.inputs.output_path || 'gs://bgg-predictive-models-dev/predictions/game_predictions.parquet' }}"
